# Experiment 10: Data Analysis and Visualization  

1. Create numpy array to find sum of all elements in an array. 

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

total = np.sum(arr)

print("Array:", arr)
print("Sum of elements:", total)

Array: [10 20 30 40 50]
Sum of elements: 150


2. Create numpy array of (3,3) dimension. Now find sum of all rows & columns 
individually. Also find 2nd maximum element in the array.   

In [2]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Array:\n", arr)

# Row-wise sum
print("Row Sum:", arr.sum(axis=1))

# Column-wise sum
print("Column Sum:", arr.sum(axis=0))

# Second maximum element
second_max = np.sort(arr.flatten())[-2]
print("Second Maximum:", second_max)

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row Sum: [ 60 150 240]
Column Sum: [120 150 180]
Second Maximum: 80


3. Perform Matrix multiplication of any 2 n*n matrices.  

In [3]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


4. Write a Pandas program to get the powers of an array values element-wise.   
Note: First array elements raised to powers from second array  
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}  
Expected Output:  
X Y Z  
0 78 84 86  
1 85 94 97  
2 96 89 96  
3 80 83 72  
4 86 86 83 

In [4]:
import pandas as pd

data = {'X':[78,85,96,80,86],
        'Y':[84,94,89,83,86],
        'Z':[86,97,96,72,83]}

df = pd.DataFrame(data)

print("Original DataFrame:\n")
print(df)

# Element-wise power (X raised to Y)
power = df['X'] ** df['Y']
print("\nX raised to power Y:\n")
print(power)

Original DataFrame:

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

X raised to power Y:

0                      0
1    4551265826121030281
2                      0
3                      0
4                      0
dtype: int64


5. Write a Pandas program to get the first 3 rows of a given DataFrame.  
Sample Python dictionary data and list labels:  
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],  
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],  
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],  
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}  
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']  
Expected Output:  
First three rows of the data frame:  
attempts name qualify score  
a 1 Anastasia yes 12.5  
b 3 Dima no 9.0  
c 2 Katherine yes 16.5  

In [5]:
import pandas as pd
import numpy as np

exam_data = {
'name': ['Anastasia','Dima','Katherine','James','Emily',
         'Michael','Matthew','Laura','Kevin','Jonas'],
'score': [12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
'attempts': [1,3,2,3,2,3,1,1,2,1],
'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)

print("First three rows of the DataFrame:\n")
print(df.head(3))

First three rows of the DataFrame:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


6. Write a Pandas program to find and replace the missing values in a given 
DataFrame which do not have any valuable information.  

In [6]:
import pandas as pd
import numpy as np

df = pd.DataFrame(exam_data)

print("Before replacing:\n")
print(df)

# Replace NaN with 0
df.fillna(0, inplace=True)

print("\nAfter replacing missing values:\n")
print(df)

Before replacing:

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

After replacing missing values:

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    0.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    0.0         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes


7. Create a program to demonstrate different visual forms using Matplotlib. 


In [7]:
import matplotlib.pyplot as plt
import numpy as np

x = np.array([1,2,3,4,5])
y = np.array([10,20,25,30,40])

# Line Plot
plt.plot(x,y)
plt.title("Line Plot")
plt.show()

# Bar Chart
plt.bar(x,y)
plt.title("Bar Chart")
plt.show()

# Scatter Plot
plt.scatter(x,y)
plt.title("Scatter Plot")
plt.show()

# Pie Chart
plt.pie(y, labels=x, autopct='%1.1f%%')
plt.title("Pie Chart")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'